config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :features do 
    resources :needs, only: [:create, :edit, :update, :destroy]
  end

  # resources :needs, only: [:destroy]  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :user
  has_many :needs, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/need.rb
class Need < ApplicationRecord
  belongs_to :user
  belongs_to :feature

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :features
  has_many :needs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :position])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :position])
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  def index
    @features = Feature.all
  end

  def show
    @needs = @feature.needs
    @need = Need.new
  end

  def new
    @feature = Feature.new
  end

  def create
    @feature = Feature.new(feature_params)
    @feature.user = current_user
    if @feature.save
      redirect_to feature_path(@feature)
    else render 'new'
    end
  end

  def edit
  end

  def update
    @feature.update(feature_params)
    if @feature.save
        redirect_to feature_path(@feature)
    else render 'edit'
    end
  end

  def destroy
    @feature.destroy
    redirect_to features_path
  end

  private

  def feature_params
    params.require(:feature).permit(:name, :description, :delivery)
  end

  def set_feature
    @feature = Feature.find(params[:id])   
  end
  
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  
  before_action :set_feature
  before_action :set_need, only: [:edit, :update, :destroy]

  def create
    @need = Need.new(need_params)
    @need.user = current_user
    @need.feature = @feature 
    if @need.save
      redirect_to feature_path(@feature)
    else
      redirect_to feature_path(@feature)
    end
  end

  def edit
  end

  def update
    @need.update(need_params)
    if @need.save
      redirect_to feature_needs_path
    else
      render 'edit'
    end
  end

  def destroy
    @need.delete 
    redirect_to feature_path(@feature)
  end

  private

  def set_feature
    @feature = Feature.find(params[:feature_id])
  end

  def set_need
    @need = Need.find(params[:id])
  end

  def need_params
    params.require(:need).permit(:description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/features/edit.html.erb
<%= form_for(@feature) do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name  %>
  <%= f.label :description  %>
  <%= f.text_field :description  %>
  <%= f.label :delivery  %>
  <%= f.text_field :delivery %>
  <%= f.submit "update feature" %>
<% end %>

<%= link_to "Revenir à la feature", feature_path(@feature)  %>

app/views/features/index.html.erb
<div class="container">
  <h1>Features list</h1>

  <ul>
    <% @features.each do |feature| %>
      <li>
        <p>
          <%= link_to feature.name, feature_path(feature)  %>
          <br> 
          description: <%= feature.description  %>
          <br> 
          product assignee: <%= feature.user.name %>
        </p>
      </li>
     <% end %>

     <%= link_to "Add a feature", new_feature_path, class: "button-blue"  %>
  </ul>
</div>

app/views/features/new.html.erb
<div class="container">
  <%= form_for(@feature) do |f| %>
    <%= f.label :name  %>
    <%= f.text_field :name  %>
    <%= f.label :description  %>
    <%= f.text_field :description  %>
    <%= f.label :delivery  %>
    <%= f.text_field :delivery %>
    <%= f.submit "Add a feature", class: "button-blue" %>
  <% end %>
</div>

app/views/features/show.html.erb
<%= link_to features_path do %>
  <i class="fas fa-times"></i>
<% end %>

<div class="container">

  <h4> <%= @feature.name %> 
    <% if current_user == @feature.user %>
      <%= link_to edit_feature_path(@feature) do  %>
        <i class="fas fa-pen"></i>
      <% end %>
    <% end %>
  </h4> 

  <p>description: <%= @feature.description %></p>

  <p>estimated delivery: 
    <%= if @feature.delivery.blank?
       "not specified"
       else @feature.delivery 
    end %> 
  </p>

  <p>product assignee: <%= @feature.user.name  %></p>

  <p><br></p>
  <p>
    <% if current_user == @feature.user %>
      <%= link_to "Delete feature", feature_path(@feature), method: :delete, data: {confirm: "Are you sure?"}, class: "button-red"  %>
    <% end %>
  </p>

  <h4>Needs list for <%= @feature.name  %></h4>

  <ul>
    <% @needs.each do |need| %>
    <li>
      <p>
        <%= need.description  %>
        <br>
        <%= need.user.name  %>
        <br>
          <% if current_user == need.user %>
            <%= link_to "Delete need", [@feature, need], method: :delete, data: {confirm: "Are you sure?"}  %>
          <% end %>
      </p>
    </li>
    <% end %>
  </ul>

  <h4>Create a need for <%= @feature.name %></h4>

  <%= form_for [@feature, @need] do |f| %>
    <%= f.text_field :description, placeholder: "Add a description"  %>
    <%= f.submit "Add a need", class: "button-blue"  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/needs/edit.html.erb
<h5>Update need</h5>

<%= form_for [@feature, @need] do |f|  %>
  <%= f.label :description  %>
  <%= f.text_field :description  %>
  <%= f.submit "update the need" %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Features", features_path, class: "navbar-wagon-item navbar-wagon-link" %>
      
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>